name: Resource Export and Deploy

on:
  workflow_dispatch:
    inputs:
      source_environment:
        description: 'Source Environment'
        required: true
        type: choice
        options:
          - dev
          - prod
      target_environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - dev
          - prod
      resource_name:
        description: 'Resource Name'
        required: true
        type: string
      commit_changes:
        description: 'Commit ARM templates to repository'
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.source_environment }}
    steps:
      - name: "Set Workflow"
        uses: cicd-templates/.github/workflows/adf-build.yaml@main
        with:
          subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resource_group: ${{ vars.SOURCE_RG }}
          data_factory_name: ${{ vars.DATA_FACTORY_NAME }}
          target_environment: ${{ github.event.inputs.target_environment }}

    

      
  # build:
  #   uses: cicd-templates/.github/workflows/wa-build-deploy.yaml@main
  #   with:
  #     subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  #     resource_group: ${{ vars.SOURCE_RG }}
  #     data_factory_name: ${{ vas,.DATA_FACTORY_NAME }}
  #     source_environment: ${{ github.event.inputs.source_environment }}
  #   secrets:
  #     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}



  # export-and-deploy:
  #   runs-on: ubuntu-latest
  #   environment: ${{ github.event.inputs.target_environment }}

    
  #   steps:

