name: Test Workflow
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string

jobs:
  test-call:
      runs-on: ubuntu-latest
      environment: ${{inputs.environment}}
      # environment: ${{ inputs.environment }}
      steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{vars.CLIENT_ID}}
          tenant-id: ${{vars.TENANT_ID}}
          subscription-id: ${{vars.SUBSCRIPTION_ID}}
      
      - name: 'Get Secrets from Key Vault'
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{vars.KEYVAULT_NAME}}
          secrets: 'TEST' 
        id: kv
      
      - name: 'Uso del secreto'
        run: |
          echo "Usando el secreto centralizado: ${{ steps.kv.outputs.TEST }}"
