name: Test Workflow
on:
  workflow_dispatch:
    inputs:
      environment-1:
        description: 'Environment for testing'
        required: true
        type: string
      environment-2:
        description: 'Environment 2 for testing'
        required: true
        type: string        


jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-1 }}
    steps:
      - name: Run Tests
        run: |
            echo The value of the variable is ${{ vars.MI_VARIABLE }}

  test-2:
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment-2 }}
      steps:
      - name: Print Environment Variable
        run: |
          echo The value of the variable is ${{ vars.MI_VARIABLE }}